// Importa los módulos necesarios
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './css/globals.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import { CartProvider } from '../../contexts/CartContext'

// Configura la fuente Inter
const inter = Inter({ subsets: ['latin'] })

// Define el componente RootLayout
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    // Usa un fragmento de React para envolver el contenido
    <>
      <html lang="en">
        <body className="font-bodyFont w-full bg-main-bg text-darkText">
          {/* Proporciona el CartProvider para envolver los componentes que necesitan acceder al contexto del carrito */}
          <CartProvider>
            <Header />
            {children}
            <Footer />
          </CartProvider>
        </body>
      </html>
    </>
  )
}

// Exporta el componente RootLayout
export default RootLayout




